/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.empyrean.disruptor;

import com.empyrean.disruptor.patterns.loadbalancer.LoadBalancer;
import com.empyrean.disruptor.patterns.mpsc.MultiProducer;
import com.empyrean.disruptor.patterns.multicast.Multicast;
import com.empyrean.disruptor.patterns.pipeline.Pipeline;
import com.empyrean.disruptor.patterns.spsc.SingleProducer;
import com.lmax.disruptor.dsl.ProducerType;

public class App {
    static int bufferSize = 1024;

    public static void main(String[] args) throws Exception {
        String mode = args.length > 0 ? args[0] : "spsc";
        DisruptorFactory factory = new DisruptorFactory(bufferSize);

        switch (mode.toLowerCase()) {
            case "spsc"      -> new SingleProducer().run(factory.create(ProducerType.SINGLE));
            case "multicast" -> new Multicast().run(factory.create(ProducerType.SINGLE));
            case "pipeline"  -> new Pipeline().run(factory.create(ProducerType.SINGLE));
            case "mpsc"         -> new MultiProducer().run(factory.create(ProducerType.MULTI));
            case "loadbalancer" -> new LoadBalancer().run(factory.create(ProducerType.SINGLE));
            default             -> throw new IllegalArgumentException("Unknown mode: " + mode + ". Use 'spsc', 'multicast', 'pipeline', 'mpsc', or 'loadbalancer'.");
        }
    }
}
