/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.empyrean.disruptor;

import com.empyrean.disruptor.patterns.multicast.Multicast;
import com.empyrean.disruptor.patterns.pipeline.Pipeline;
import com.empyrean.disruptor.patterns.spsc.SingleProducer;
import com.lmax.disruptor.dsl.Disruptor;
import com.lmax.disruptor.util.DaemonThreadFactory;

public class App {
    static int bufferSize = 1024;

    public static void main(String[] args) throws Exception {
        String mode = args.length > 0 ? args[0] : "spsc";
        Disruptor<Quote> disruptor = new Disruptor<>(Quote::new, bufferSize, DaemonThreadFactory.INSTANCE);

        switch (mode.toLowerCase()) {
            case "spsc"      -> runSpsc(disruptor);
            case "multicast" -> runMulticast(disruptor);
            case "pipeline"  -> runPipeline(disruptor);
            default          -> throw new IllegalArgumentException("Unknown mode: " + mode + ". Use 'spsc', 'multicast', or 'pipeline'.");
        }
    }

    private static void runSpsc(Disruptor<Quote> disruptor) throws Exception {
        new SingleProducer(disruptor, bufferSize).run();
    }

    private static void runMulticast(Disruptor<Quote> disruptor) throws Exception {
        new Multicast(disruptor).run();
    }

    private static void runPipeline(Disruptor<Quote> disruptor) throws Exception {
        new Pipeline(disruptor).run();
    }
}
