/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.empyrean.disruptor;

import java.nio.ByteBuffer;

import com.lmax.disruptor.RingBuffer;
import com.lmax.disruptor.dsl.Disruptor;
import com.lmax.disruptor.util.DaemonThreadFactory;

public class App {
    static int bufferSize = 1024;

    public static void main(String[] args) throws Exception {
        Disruptor<Quote> disruptor = new Disruptor<>(Quote::new, bufferSize, DaemonThreadFactory.INSTANCE);

        disruptor.handleEventsWith(new QuoteEventHandler(), new LoggingEventHandler());
        disruptor.start();

        RingBuffer<Quote> ringBuffer = disruptor.getRingBuffer();
        ByteBuffer bb = ByteBuffer.allocate(8);
        for (long l = 0; true; l++) {
            bb.putLong(0, l);
            ringBuffer.publishEvent((event, sequence, buffer) -> event.set("QUOTE", (float) buffer.getLong(0)), bb);
        }
    }
}
